### ISSUE TITLE
Received an unexpected return code from 'ansible-lint'.

### ISSUE THREAD

**Issue by chilicheech** [4ch1m/intellij-ansible-lint#1]
I just installed the plugin. Thanks for it. I get this error when it runs. In the settings I set the path to `/usr/local/bin/ansible-lint` which is where homebrew installs it by default on OSX. However, the project I'm working on is using a python virtualenv created by pyenv, hence why I forced the full path otherwise the plugin complains it can't find ansible-lint even though it is also installed in the virtualenv.

Here are some logs:
```
2023-02-06 13:24:39,248 [ 588328] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH
java.lang.Throwable: Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH
```
```
java.lang.Throwable: Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:83)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:35)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:209)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:203)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:278)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:344)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:334)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:281)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:238)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:377)
	at com.intellij.util.Alarm$Request.run(Alarm.java:366)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
However:
```
➜  ~ echo $PATH
/usr/local/Cellar/pyenv-virtualenv/1.2.1/shims:/Users/me/.pyenv/shims:/Users/me/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin
➜  ~ which ansible
/Users/me/.pyenv/shims/ansible
➜  ~ pyenv which ansible
/usr/local/bin/ansible
➜  ~ which ansible-lint
/Users/me/.pyenv/shims/ansible-lint
➜  ~ pyenv which ansible-lint
/usr/local/bin/ansible-lint
➜  ~
```

This is possibly a similar issue the `pylint` and `mypy` plugins had early on. They found a way to fix it or get around it. Perhaps the same needs to be done with this plugin?

Cheers,

**Comment by 4ch1m** [comment]
Hey there,

thanks for your report.
I just created a fix; which adds the system's environment variables when calling `ansible-lint`: f4dd061f4107cd33ca4c8db6cfd562e8d23c455f

Hope this will resolve your issue.
(Let me know if it doesn't.)

The updated plugin version should be available in the marketplace within the next two business days.

**Comment by chilicheech** [comment]
Thanks for the quick response. I just got the update to 1.2.1. Now running into a different issue:

![Screen Shot 2023-02-07 at 12 37 55 PM](https://user-images.githubusercontent.com/732659/217360025-9e6c7012-64f3-4d98-916d-38c37fbf1a48.png)
```
2023-02-07 12:51:34,707 [1021638] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH

java.lang.Throwable: Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:83)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:35)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:209)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:203)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:278)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:181)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:344)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:180)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:334)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:281)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:238)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:377)
	at com.intellij.util.Alarm$Request.run(Alarm.java:366)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-07 12:51:34,709 [1021640] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-02-07 12:51:34,709 [1021640] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-02-07 12:51:34,709 [1021640] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - OS: Mac OS X
2023-02-07 12:51:34,709 [1021640] SEVERE - #de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator - Plugin to blame: Ansible Lint version: 1.2.1
```

```
➜  ~ type /usr/local/bin/ansible-lint
/usr/local/bin/ansible-lint is /usr/local/bin/ansible-lint
➜  ~ which ansible-lint
/Users/me/.pyenv/shims/ansible-lint
➜  ~ pyenv which ansible-lint
/usr/local/bin/ansible-lint
➜  ~ ansible-lint --version
ansible-lint 6.12.1 using ansible 2.14.2
➜  ~
```

```
➜  ~ type /usr/local/bin/ansible
/usr/local/bin/ansible is /usr/local/bin/ansible
➜  ~ which ansible
/Users/me/.pyenv/shims/ansible
➜  ~ pyenv which ansible
/usr/local/bin/ansible
➜  ~ ansible --version
ansible [core 2.14.2]
  config file = /Users/me/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/7.2.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.1 (main, Dec 23 2022, 09:40:27) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/Cellar/ansible/7.2.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
➜  ~
```

And if I let it use the pyenv virtualenv I get the following:
![Screen Shot 2023-02-07 at 12 44 41 PM](https://user-images.githubusercontent.com/732659/217361415-69b9141a-d1f8-4761-bb1e-cd98280a69d9.png)

```
(venv) ➜  playbooks git:(dev) ✗ which ansible-lint
/Users/me/.pyenv/shims/ansible-lint
(venv) ➜  playbooks git:(dev) ✗ pyenv which ansible-lint
/Users/me/.pyenv/versions/venv/bin/ansible-lint
(venv) ➜  playbooks git:(dev) ✗ ansible-lint --version
ansible-lint 6.12.1 using ansible 2.14.2
(venv) ➜  playbooks git:(dev) ✗
```

```
(venv) ➜  playbooks git:(dev) ✗ which ansible
/Users/me/.pyenv/shims/ansible
(venv) ➜  playbooks git:(dev) ✗ pyenv which ansible
/Users/me/.pyenv/versions/venv/bin/ansible
(venv) ➜  playbooks git:(dev) ✗ ansible --version
ansible [core 2.14.2]
  config file = /Users/me/.ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/me/.pyenv/versions/3.9.15/envs/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/me/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/me/.pyenv/versions/venv/bin/ansible
  python version = 3.9.15 (main, Nov 13 2022, 20:18:38) [Clang 14.0.0 (clang-1400.0.29.202)] (/Users/me/.pyenv/versions/3.9.15/envs/venv/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
(venv) ➜  playbooks git:(dev) ✗
```
The SDK is set to that pyenv virtualenv.

**Comment by 4ch1m** [comment]
I'm afraid I can't help you with your ansible/ansible-lint setup, since it seems pretty Mac-specific to me.

When you open a terminal, and enter this ...

```
ansible-lint --version
```

... you should get something like this:

```
ansible-lint 6.12.1 using ansible 2.14.1
```

Any of your virtual environments are **NOT** automatically detected or activated by the plugin.

My suggestion would be as follows:

* create a dedicated venv for ansible-lint: `python3 -m venv ~/ansible-lint-venv`
* activate it: `source ~/ansible-lint-venv/bin/activate`
* install ansible-lint: `(ansible-lint-venv) ➜ pip install ansible-lint`
* now exit the venv: `(ansible-lint-venv) ➜ deactivate`
* create a shell-script in your bin-folder: `vi ~/bin/ansible-lint-venv`
* add this content:  
  ```
   #!/bin/bash
   source ~/ansible-lint-venv/bin/activate
   ansible-lint ${@}
  ```
* make it executable: `chmod +x ~/bin/ansible-lint-venv`

finally...
Add `/home/{your_username}/bin/ansible-lint-venv` as full path in the plugin.

That definitely should work.

**Comment by chilicheech** [comment]
So my terminal does return the ansible-lint version when I run the command in my terminal. I pasted the output in the previous comments. I tried something similar to what you suggested and it worked, without sourcing the activate file:
```
#!/bin/bash
/Users/me/.pyenv/versions/venv/bin/ansible-lint ${@}
```
I suspect the issue is how `pyenv` handles executables. It creates "shims" that point to the correct executable based on which python virtual env is active or if there are no active virtual envs. This is what a pyenv "shim" looks like:
```
➜  ~ which ansible-lint
/Users/me/.pyenv/shims/ansible-lint
➜  ~ cat /Users/me/.pyenv/shims/ansible-lint
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"

export PYENV_ROOT="/Users/me/.pyenv"
exec "/usr/local/opt/pyenv/bin/pyenv" exec "$program" "$@"
➜  ~
```
A long time ago when the IDEA pylint and mypy plugins were new, they had the same issue we're experiencing here. They were able to somehow add support for `pyenv` shim files. Please take a look at those projects and see if you can add it here too.

Thanks for your help. I'll use the workaround for now.

Cheers.
