### ISSUE TITLE
Trouble getting the plugin working

### ISSUE THREAD

**Issue by gaufde** [4ch1m/intellij-ansible-lint#20]
Hello,

I am having some trouble getting the plugin working. I have installed `ansible` and `ansible-lint` in a virtual environment. I followed the README instructions to create a small shell script, and that seems to be working:
<img width="982" alt="image" src="https://github.com/user-attachments/assets/b798ffaf-6b1a-4345-80af-849e138cbc08">

I have a minimal `.ansible-lint` file like this:
```
---
# created by 'IntelliJ Ansible Lint Plugin'
#
# check this website for detailed configuration options:
#    https://ansible-lint.readthedocs.io/configuring/#ansible-lint-configuration

profile: production
use_default_rules: true
```

When I run my executable `run_ansible-lint.sh` file, I do get output which shows me `ansible-lint` is installed and working correctly with my `.ansible-lint` config file:
<img width="939" alt="image" src="https://github.com/user-attachments/assets/a3e0d8ef-2809-4508-9b15-fa623d55ba5c">

However, when I edit a test playbook, I don't see any issues or suggestions pop up:
<img width="1730" alt="image" src="https://github.com/user-attachments/assets/06839e85-c699-42b6-ab3a-1992e9607530">

I am on Mac OS 13.6.7, PyCharm 2024.1.5, and Ansible Lint plugin 1.7.1. 

Does anyone have suggestions for what to try next? I am new to Ansible in general, so there could be other configuration requirements I haven't found in the docs yet.

**Comment by gaufde** [comment]
I just tried updating PyCharm to 2024.2.0.1 and the Ansible Lint plugin to 1.8.0. Now, on startup I'm seeing this pop up:
<img width="579" alt="image" src="https://github.com/user-attachments/assets/c0b6ee55-d206-480b-ac2e-dc3e1d4f65b8">


Unfortunately, I don't know how to submit this report since typing in the highlighted box doesn't seem to work:
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/9fe615fd-be18-4aff-9356-d98ac5ce2d27">

That said, here are the lines that I can see:
```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator@49aa5138 (class de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator) [Plugin: de.achimonline.ansible_lint]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:253)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:213)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:200)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:163)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:268)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:163)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:161)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:366)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:356)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:313)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:295)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:262)
	at com.intellij.util.Alarm$Request.lambda$runSafely$0(Alarm.java:371)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.util.Alarm$Request.lambda$runSafely$1(Alarm.java:369)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:255)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:356)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:383)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: getParent(...) must not be null
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:66)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:40)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.lambda$doAnnotate$1(ExternalToolPass.java:208)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:206)
	... 43 more
```

**Comment by 4ch1m** [comment]
Did you install the `OrchidE` plugin as well? (see https://github.com/4ch1m/intellij-ansible-lint/issues/16#issuecomment-2004372483)
There are known conflicts.

**Comment by gaufde** [comment]
> Did you install the `OrchidE` plugin as well? (see [#16 (comment)](https://github.com/4ch1m/intellij-ansible-lint/issues/16#issuecomment-2004372483)) There are known conflicts.

No, I have never used that plugin before. I did briefly download this other [Ansible plugin](https://plugins.jetbrains.com/plugin/14893-ansible); however, I have uninstalled it. I've also disabled all other non-default plugins temporarily:
<img width="986" alt="image" src="https://github.com/user-attachments/assets/20bf5797-75ac-4846-b276-33382e30b39a">

**Comment by 4ch1m** [comment]
After taking a closer look at the stacktrace above...
I believe your setup is correct. And I believe you've found a bug. :smile:

I already prepared a [fix](https://github.com/4ch1m/intellij-ansible-lint/commit/e100bf68bce435c15f49036e872902d14f729287#diff-4c3436f3fe074733621ffc141613130f08421382d516d57775098e4280b20261).

The updated plugin (`v1.8.1`) should be available in the marketplace soon.

Please let me know if this solves your issues. Thanks.

**Comment by gaufde** [comment]
I think that did the trick! Thanks for the prompt support, I really appreciate it.
_____
Now that it is working, I've noticed a curious thing that I'd be interested to know if it is expected behavior or not. It seems like the plugin doesn't show some errors until others are fixed.

For example, on this file I see:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3179f264-8ec0-4bcb-a2eb-e155c0bb1be3">

However, if I run `ansible-lint` in the command line I see:
<img width="1642" alt="image" src="https://github.com/user-attachments/assets/89eb0ef9-03f7-4f8d-94aa-72efe75836f7">

If I fix the first error, then the plugin shows me the second one:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/d68a2615-f0cb-4de6-b8d7-ceec4a3fe4f9">

This is totally usable, but I'm curious if it is normal or not.

**Comment by 4ch1m** [comment]
> This is totally usable, but I'm curious if it is normal or not.

Totally normal; and totally correct.
Your errors are referring to the **same** task/line.
If you hover your mousepointer over the annotation, then you'll see both errors displayed.

Thanks for reporting back.

**Comment by gaufde** [comment]
Great! That is good to know. I won't worry about it then, though FYI I'm not seeing the mouse-over behavior just in case that detail matters to you. Otherwise, I'm content since now I can get on with the rest of my project!
<img width="1731" alt="image" src="https://github.com/user-attachments/assets/dc52f6b9-1675-453f-85e1-5c11cfb9f7ad">

**Comment by 4ch1m** [comment]
Not sure why only one error gets shown with your setup.

I just tested it on a fresh project (default settings); all errors/warnings are available:

![image](https://github.com/user-attachments/assets/c3b42df1-01b7-4d3e-8a6e-1c504df50242)

Let me know if you find the root cause. Thanks a lot.

**Comment by gaufde** [comment]
Oh interesting! I'll have to play with it a bit more then.

How do you have python and ansible-lint installed? I think I would like to try replicating that next.

I've been using python installed via Homebrew. I just tried downloading python directly from python.org.

Then I ran this in zsh:
```
which python3                           
/Library/Frameworks/Python.framework/Versions/3.12/bin/python3

python3 -m pip install ansible-dev-tools
```

After that, running `ansible-lint` works directly in my terminal without using or activating a virtual environment. However, if I try to switch away from using the run script in the plugin, it seems that it can't find `ansible-lint`:
<img width="938" alt="image" src="https://github.com/user-attachments/assets/454bb6b6-7e85-4871-a0bb-3275d96fc801">

I'm not sure that this would have any impact on how the errors get displayed, but maybe if I can replicate your environment more closely I can track down what is different between our machines.
