### ISSUE TITLE
ExternalToolPass Error in Webstorm 2024.3 with plugin version 1.9.0

### ISSUE THREAD

**Issue by kpervin** [4ch1m/intellij-ansible-lint#25]
```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator@723be06d (class de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator) [Plugin: de.achimonline.ansible_lint]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:272)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:229)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:216)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:174)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:287)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:174)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:172)
	at com.intellij.util.ui.update.Update.execute$suspendImpl(Update.kt:61)
	at com.intellij.util.ui.update.Update.execute(Update.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue.executeUpdates$suspendImpl(MergingUpdateQueue.kt:371)
	at com.intellij.util.ui.update.MergingUpdateQueue.executeUpdates(MergingUpdateQueue.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invokeSuspend(MergingUpdateQueue.kt:351)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invoke(MergingUpdateQueue.kt)
	at com.intellij.util.ui.update.MergingUpdateQueue$restart$1.invoke(MergingUpdateQueue.kt)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invokeSuspend(SingleAlarm.kt:394)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invoke(SingleAlarm.kt)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1$1.invoke(SingleAlarm.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.util.SingleAlarm$scheduleTask$1$1.invokeSuspend(SingleAlarm.kt:392)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: java.lang.IllegalArgumentException: Trying to get WSL path from a different WSL distribution. Requested path (\\wsl.localhost\Ubuntu\home\kpervin\projects\project\.ansible-lint) belongs to Ubuntu distribution, but context distribution is \\wsl.localhost\Ubuntu\home\kpervin\projects\project
	at com.intellij.execution.wsl.WSLDistribution.getWslPath(WSLDistribution.java:607)
	at de.achimonline.ansible_lint.command.AnsibleLintCommandLineWSL.createLintProcess(AnsibleLintCommandLineWSL.kt:44)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:103)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:43)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.lambda$doAnnotate$1(ExternalToolPass.java:224)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.AnnotationSessionImpl.computeWithSession(AnnotationSessionImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:222)
	... 36 more
```

**Comment by 4ch1m** [comment]
Hmmm... this might be related to [this](https://github.com/4ch1m/intellij-ansible-lint/issues/21#issuecomment-2450206544). :thinking:

**Comment by kpervin** [comment]
> Hmmm... this might be related to [this](https://github.com/4ch1m/intellij-ansible-lint/issues/21#issuecomment-2450206544). 🤔

I am using [devbox ](https://www.jetify.com/docs/devbox/quickstart/) to install `ansible-lint`, and it seems to be picked up by your plugin:

![image](https://github.com/user-attachments/assets/809c9560-7749-4db1-8446-7c51befc3709)

However, something seems wrong with when it attempts to pick up the `.ansible-lint` config at the root of the project:

```yaml
---
# created by 'IntelliJ Ansible Lint Plugin'
#
# check this website for detailed configuration options:
#    https://ansible-lint.readthedocs.io/configuring/#ansible-lint-configuration

profile: null
use_default_rules: true
exclude_paths:
  - .cache/ # implicit unless exclude_paths is defined in config
  - .bootstrap/
  - .github/
  - .flakes/
  - .venv/
  - .devbox/
kinds:
  - playbook: "**/*.playbook.{yml,yaml}"
```

let me know if there's anything else I can help with? I also attempted to use `.config/ansible-lint.yml` that was auto-generated by the plugin, but I got the same `Caused by: java.lang.IllegalArgumentException: Trying to get WSL path from a different WSL distribution. Requested path (\\wsl.localhost\Ubuntu\home\kpervin\projects\project\.config\ansible-lint.yml) belongs to Ubuntu distribution, but context distribution is \\wsl.localhost\Ubuntu\home\kpervin\projects\project` message.

**Comment by 4ch1m** [comment]
Thanks for the feedback, @kpervin .
I'm not actively using Windows myself; so I'll have to use another machine/development-setup to dig deeper into this issue (which might take a while).
However, it would be cool if someone (using Windows) could debug this and provide a suitable fix.

**Comment by 4ch1m** [comment]
@kpervin: Do you have multiple WSL distributions installed? (`wsl.exe --list`)

What happens if you change the default distribution? ([change-the-default-linux-distribution-installed](https://learn.microsoft.com/en-us/windows/wsl/install#change-the-default-linux-distribution-installed))

I only tested everything with one distro ("Ubuntu") installed.
I guess I'll have to implement a "distro selection box" in the settings dialog.

**Comment by kpervin** [comment]
@4ch1m I am not using multiple distributions; just the default Ubuntu 22.04. I've tried pointing to both the DevBox install of Ansible Lint as well as one installed by apt, but the issue occurs when pointing at either.

**Comment by 4ch1m** [comment]
@kpervin OK. Thanks for the feedback.
I'll try to improve the WSL-setup/-usage by properly handling the distribution configuration.
Hopefully that will resolve the issues.

**Comment by kpervin** [comment]
Thanks @4ch1m! Let me know if there's anything else I can do to help.

**Comment by 4ch1m** [comment]
OK...
So I've improved the WSL-feature by making the distro selectable/configurable: 10bd82a798a8d609c2d123f18cfd8bdf0051bce9

I hope this will resolve the issue and no longer lead to this error: "Trying to get WSL path from a different WSL distribution."

The new version (`1.10.0`) of the plugin should be available in the JetBrains marketplace soon.

Would be cool if you could let me know if this works for you too.

Thanks!

**Comment by kpervin** [comment]
> OK... So I've improved the WSL-feature by making the distro selectable/configurable: [10bd82a](https://github.com/4ch1m/intellij-ansible-lint/commit/10bd82a798a8d609c2d123f18cfd8bdf0051bce9)
> 
> I hope this will resolve the issue and no longer lead to this error: "Trying to get WSL path from a different WSL distribution."
> 
> The new version (`1.10.0`) of the plugin should be available in the JetBrains marketplace soon.
> 
> Would be cool if you could let me know if this works for you too.
> 
> Thanks!

Excellent! I'll give it a go tomorrow and report back. Thank you!

**Comment by kpervin** [comment]
Seems to work! Thanks!

**Comment by 4ch1m** [comment]
Awesome, thanks for the feedback.
