### ISSUE TITLE
Can't seem to get this to work on MacOS

### ISSUE THREAD

**Issue by notfixingit3** [4ch1m/intellij-ansible-lint#6]
With ansible and ansible-lint installed via pip or via brew (yes, I know this option is not supported) results in in the following error.  I'm not sure what other ways to try? ansible is for sure installed and works via terminal. This was a breeze on Linux but can not seem to get it to work on MacOS

java.lang.Throwable: Unexpected exit code from 'ansible-lint': 1; |Failed to find runtime dependency 'ansible' in PATH

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:99)
	at de.achimonline.ansible_lint.annotator.AnsibleLintAnnotator.doAnnotate(AnsibleLintAnnotator.kt:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:201)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:164)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:266)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:162)
	at com.intellij.util.ui.update.Update.runUpdate(Update.java:114)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:348)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:338)
	at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:295)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:277)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)
	at com.intellij.util.Alarm$Request.run(Alarm.java:360)
	at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 4ch1m** [comment]
The error message (which obviously originates from `ansible-lint`) clearly says that `ansible` itself is missing in your `PATH`.

As described in the [README](https://github.com/4ch1m/intellij-ansible-lint#requirements) you should try to create a Bash script to invoke `ansible-lint` and refer to that Bash script in your IntelliJ-Plugin setup.

**Comment by notfixingit3** [comment]
I was able to figure it out. For what ever reason, Intellij drops  "/usr/local/bin" from it's PATH when calling ansible-lint. My solution was similar to what was in your readme. I simple created the below script ansible-lint-pathfix.sh and set it to this in the plugin setup. 

For Intel Macs:
#!/bin/bash
export PATH=$PATH:/usr/local/bin
ansible-lint ${@}

For Apple Silicon:
#!/bin/bash
export PATH=$PATH:/usr/local/bin:/opt/homebrew/bin
ansible-lint ${@}

Note tested this solution with both pip and brew installs of ansible/ansible-lint on MacOS and it seems to function correctly with it.

Thanks for your great work!
